[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-DNS-Prefetch-Control = "on"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self' blob: 'unsafe-inline' 'unsafe-eval' *.funet.fi https://cdn.jsdelivr.net; media-src 'self' blob: *.funet.fi; connect-src *; img-src 'self' * blob: data: https://api.finna.fi; style-src 'self' 'unsafe-inline'"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
