name: Download static data
on: workflow_dispatch
jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install
        run: npm i
      - name: Download
        run: node .next/server/download.js
      - name: Build site
        run: npm build; npm export
